Repository RodrigoFranca2004/sustento-back, pull requests merged in 2025-09, with the labels that each got.

#1 Refactor/restructure prisma architecture
  prisma/migrations/20250903005056_rename_user_to_users/migration.sql
  prisma/migrations/20250904011352_fix_user_id/migration.sql
  prisma/schema.prisma
  src/app.js
  src/app/server.js
  src/config/prisma.js
  src/controllers/user.controller.js
  src/entities/User.js
  src/index.js
  src/repositories/user.repository.js
  src/routes/index.js
  src/routes/router.js
  src/routes/user.routes.js
  src/services/user.service.js
Labels: documentation, enhancement

#2 Feat hash password
  package-lock.json
  package.json
  prisma/migrations/20250906201840_fix_decimal_places/migration.sql
  prisma/schema.prisma
  src/services/user.service.js
Labels: documentation, enhancement

#3 created restriction and user_evolution tables
  prisma/migrations/20250907021527_add_restriction_table/migration.sql
  prisma/migrations/20250907022702_refactor_restriction_name/migration.sql
  prisma/migrations/20250907151620_created_user_evolution_table/migration.sql
  prisma/schema.prisma
  src/controllers/restriction.controller.js
  src/controllers/user_evolution.controller.js
  src/routes/index.js
  src/routes/restriction.routes.js
  src/routes/user_evolution.routes.js
  src/services/restriction.service.js
  src/services/user_evolution.service.js
Labels: enhancement

#7 Feat/crud user restriction
  prisma/migrations/20250907210910_/migration.sql
  prisma/schema.prisma
  src/controllers/userEvolution.controller.js
  src/controllers/userRestriction.controller.js
  src/routes/index.js
  src/routes/userEvolution.routes.js
  src/routes/userRestriction.routes.js
  src/services/userEvolution.service.js
  src/services/userRestriction.service.js
Labels: enhancement

#9 Feat/crud meal aliments
  prisma/migrations/20250907234241_add_meal_aliments_table/migration.sql
  prisma/schema.prisma
  src/controllers/mealAliment.controller.js
  src/routes/index.js
  src/routes/mealAliment.routes.js
  src/services/aliment.service.js
  src/services/mealAliment.service.js
Labels: enhancement

#13 Feat/crud new func calc bmi
  prisma/migrations/20250921023344_added_bmi/migration.sql
  prisma/schema.prisma
  src/services/user.service.js
Labels: enhancement

#14 Fix/id on login
  src/controllers/auth.controller.js
  src/services/auth.service.js
Labels: enhancement

#15 updated the data base structure to fit water consumption
  prisma/migrations/20250927235143_fix/migration.sql
  prisma/schema.prisma
Labels: enhancement

#16 Feat/implement calories count
  src/routes/auth.routes.js
  src/services/mealPlan.service.js
Labels: enhancement, question
